### ISSUE TITLE
Handle existing tags better 

### ISSUE THREAD

**Issue by saintedlama** [versionize/versionize#20]
In case a tag already exists emit a useful error message and do not create a commit with updated version and changelog

**Current error message**
```
Unhandled exception. LibGit2Sharp.NameConflictException: tag already exists
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_tag_create(RepositoryHandle repo, String name, GitObject target, Signature tagger, String message, Boolean allowOverwrite)
   at LibGit2Sharp.TagCollection.Add(String name, GitObject target, Signature tagger, String message, Boolean allowOverwrite)
   at LibGit2Sharp.TagCollection.Add(String name, GitObject target, Signature tagger, String message)
   at Versionize.WorkingCopy.Versionize(Boolean dryrun, Boolean skipDirtyCheck, Boolean skipCommit, String releaseVersion, Boolean ignoreInsignificant, Boolean includeAllCommitsInChangelog) in C:\p\github\versionize\Versionize\WorkingCopy.cs:line 124
   at Versionize.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\p\github\versionize\Versionize\Program.cs:line 36
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass148_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Versionize.Program.Main(String[] args) in C:\p\github\versionize\Versionize\Program.cs:line 50
```

**Comment by saintedlama** [comment]
Fixed
