### ISSUE TITLE
Exclude folder from being scanned

### ISSUE THREAD

**Issue by AlexZeitler** [versionize/versionize#82]
In the root folder of my git repository I have folder `data` which has subfolders created in the context of Docker containers.

Hence I don't have read or write permissions by the user running `versionize`, hence getting this exception when running `versionize`:

```text
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/home/.../data/global' is denied.
```

Is it possible to exclude folders from the scan done by `versionize`?

I tried `versionize -w <folderwithprojectobeversionized>` to only specify the folder where the project to be versionized but the scan still seems to happen.

My folder structure is something like:

```text
. git
- data
  - global // this is created by a container
- src
  - folderwithprojectobeversionized
```

So I ran `versionize -w src/folderwithprojectobeversionized`.

I also tried to use `-w` with an absolute path.

I want to avoid deleting the `data/global` folder an running a `chown -R myuser:myuser data/global` makes the container fail.

**Comment by cabauman** [comment]
Does the stack trace happen to include where in the Versionize project that exception originated from?

**Comment by AlexZeitler** [comment]
```text
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.DequeueNextDirectory()
   at System.IO.Enumeration.FileSystemEnumerator`1.DirectoryFinished()
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Versionize.Projects.<>c__DisplayClass6_0.<Discover>b__0(String filter) in /home/runner/work/versionize/versionize/Versionize/Projects.cs:line 37
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Versionize.WorkingCopy.Versionize(VersionizeOptions options) in /home/runner/work/versionize/versionize/Versionize/WorkingCopy.cs:line 48
   at Versionize.Program.<>c__DisplayClass0_0.<Main>b__1() in /home/runner/work/versionize/versionize/Versionize/Program.cs:line 70
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Versionize.Program.Main(String[] args) in /home/runner/work/versionize/versionize/Versionize/Program.cs:line 79
[1]    1571791 IOT instruction (core dumped)  versionize
``

**Comment by AlexZeitler** [comment]
Thanks, now it works :+1:
